blank_issues_enabled: false
contact_links:
  - name: I have a question / I need help
    url: https://github.com/goong-io/goong-map-react/discussions
    about: Ask generic questions or request help here
